### ISSUE TITLE
changes to src/tomography in progress

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d_globe#330]
This issue was originally discussed as #420 on the SPECFEM3D github page.

To maintain consistency, I will go ahead and make corresponding changes to SPECFEM3D_GLOBE.

To distinguish between postprocessing and optimization routines, a new subdirectory, `src/postprocess`, will be created.  

I hope others will find this more clear because, instead of having a mix of coding conventions within the same directory, all the routines within `src/tomography` will follow one consistent convention, and all the routines within `src/postprocess` will follow another.

**Comment by QuLogic** [comment]
(PS: Use geodynamics/specfem3d#420 for auto-linking.)

**Comment by rmodrak** [comment]
Hi Elliot, 

There are a few nuances concerning the make system I don't fully understand, in particular the way dependencies on `values_from_mesher.h` are handled. If you notice any problems with `src/postprocess/rules.mk` in the upcoming pull request, please feel free to comment.

Thanks,
Ryan

**Comment by QuLogic** [comment]
Hi Ryan,

For `tomography`, the dependency is defined [here](https://github.com/geodynamics/specfem3d_globe/blob/master/src/tomography/rules.mk#L301):
```make
$O/%.tomo_module.o: $S/%.f90 ${SETUP}/constants_tomography.h ${OUTPUT}/values_from_mesher.h $O/shared_par.shared_module.o
    ${FCCOMPILE_CHECK} ${FCFLAGS_f90} -c -o $@ $<
```

In general, the convention (introduced by @danielpeter I think) is that the extension defines the "type" of file. In this case, `.tomo_module.o` depends on `values_from_mesher.h`.

That being said, it's good you brought this up, because many of the dependencies are _wrong_. Several files depend on `values_from_mesher.h` instead of `use`-ing the common module, and the Makefile does not specify that dependency.

**Comment by rmodrak** [comment]
If I understand though, the above dependency assumes that `values_from_mesher.h` already exists, which it might not.  I am finding that if some of the individual executables are removed from the targets list, `values_from_mesher.h` will not be created and compilation will fail.

**Comment by QuLogic** [comment]
There is a rule in the `create_header_file` directory that tells make how to build `values_from_mesher.h`. As I pointed out, some executables do not correctly use `values_from_mesher.h`, and thus it does not get rebuilt.

**Comment by QuLogic** [comment]
I've opened #331 to fix the use of `values_from_mesher.h`.

**Comment by rmodrak** [comment]
Pull request #331 seems to do the trick.  Thanks for the fix.

**Comment by rmodrak** [comment]
UPDATE:  I've created a subdirectory src/postprocess and moved some routines into it.  I'm still working on improving the consistency of routines within this subdirectory.

**Comment by rmodrak** [comment]
UPDATE:

Without breaking existing command line interfaces, a number of changes have been made to the src/postprocess utilities to increase flexibility. All the routines in src/postprocess have been tested and seem to be working.

If there are no other comments, I'll go ahead and close this issue later today or tomorrow.
