### ISSUE TITLE
command line arguments for xsmooth_sem differ between packages

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d_globe#336]
SPECFEM3D:
sigma_h
sigma_v
kernel_filename
input_dir
output_dir

SPECFEM3D_GLOBE:
sigma_h
sigma_v
kernel_filename
scratch_file_dir
topo_dir

If there are no objections, I will modify SPECFEM3D_GLOBE to make it consistent with the SPECFEM3D.

(Removing `topo_dir` would be accomplished by adding a `read_parameter_file` call and using the value of `LOCAL_PATH`.)

**Comment by komatits** [comment]
Very good idea!

Dimitri.

On 03/03/2015 01:56 AM, rmodrak wrote:
> SPECFEM3D:
> sigma_h
> sigma_v
> kernel_filename
> input_dir
> output_dir
>
> SPECFEM3D_GLOBE:
> sigma_h
> sigma_v
> kernel_filename
> scratch_file_dir
> topo_dir
>
> If there are no objections, I will modify the SPECFEM3D_GLOBE syntax to
> make it consistent with the SPECFEM3D syntax.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/336>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Carried out as of 92c3d0f4caf4f2d475ab48ca2702f8edfec3d942.

If it's alright, I'll go ahead and close.
