### ISSUE TITLE
code not compiling

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d_globe#378]
Using Intel 14.0

      ./configure FC=ifort CC=icc MPIFC=mpif90 MPICC=mpicc

     make -j 8

    ifort -g   -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03  -   
    diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -
    DFORCE_VECTORIZATION -mod ./obj -I./obj -I.  -I. -I./setup -c -o 
    obj/write_movie_output.solverstatic.o src/specfem3D/write_movie_output.f90
    src/specfem3D/write_movie_output.f90(52): error #6401: The attributes of this name conflict with those
    made accessible by a USE statement.   [SCALINGVAL]
    double precision :: scalingval
     ----------------------^
     compilation aborted for src/specfem3D/write_movie_output.f90 (code 1)

This first appeared with @danielpeter commit: d5649d5

**Comment by komatits** [comment]
Already fixed (does not happen with the current devel).

On 05/01/2015 09:14 PM, David Luet wrote:
> Using Intel 14.0
>
> |   ./configure FC=ifort CC=icc MPIFC=mpif90 MPICC=mpicc
>
>   make -j 8
>
>
> ifort -g   -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03  -
> diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -
> DFORCE_VECTORIZATION -mod ./obj -I./obj -I.  -I. -I./setup -c -o
> obj/write_movie_output.solverstatic.o src/specfem3D/write_movie_output.f90
> src/specfem3D/write_movie_output.f90(52): error #6401: The attributes of this name conflict with those
> made accessible by a USE statement.   [SCALINGVAL]
> double precision :: scalingval
>   ----------------------^
>   compilation aborted for src/specfem3D/write_movie_output.f90 (code 1)
> |
>
> This first appeared with @danielpeter <https://github.com/danielpeter>
> commit: d5649d5
> <https://github.com/geodynamics/specfem3d_globe/commit/d5649d507f0ee7a7e9cee72a9643680e0894063c>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/378>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
