### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d_globe#379]
Another problem.

    ifort -g   -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03 -
    diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -
    DFORCE_VECTORIZATION -mod ./obj -I./obj -I.  -I. -I./setup -c -o obj/get_attenuation.solverstatic.o 
    src/specfem3D/get_attenuation.f90
    src/specfem3D/get_attenuation.f90(35): error #6580: Name in only-list does not exist.     
    [I_SHOULD_READ_THE_DATABASE]
          I_should_read_the_database
    ------^
I believe this problem was fixed in @mpbl commit fbe890d but reintroduced in @danielpeter commit 2051275255b.
I am not sure why buildbot didn't catch these errors. Maybe its because I just updated the Intel compilers and the old ones didn't catch the mistakes? I'll investigate.

**Comment by luet** [comment]
I confirm that I don't get this error with Intel 13.0 but I get it with 14.0.
Buildbot is using 14.0 now.

**Comment by komatits** [comment]
Thanks! I'll fix them later today. (for both codes)

On 05/01/2015 10:03 PM, David Luet wrote:
> I confirm that I don't get this error with Intel 13.0 but I get it with
> 14.0.
> Buildbot is using 14.0 now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/379#issuecomment-98220979>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Fixed.

On 05/01/2015 09:25 PM, David Luet wrote:
> Another problem.
>
> |ifort -g   -xHost -fpe0 -ftz -assume buffered_io -assume byterecl -align sequence -vec-report0 -std03 -
> diag-disable 6477 -implicitnone -gen-interfaces -warn all -O3 -check nobounds -
> DFORCE_VECTORIZATION -mod ./obj -I./obj -I.  -I. -I./setup -c -o obj/get_attenuation.solverstatic.o
> src/specfem3D/get_attenuation.f90
> src/specfem3D/get_attenuation.f90(35): error #6580: Name in only-list does not exist.
> [I_SHOULD_READ_THE_DATABASE]
>        I_should_read_the_database
> ------^
> |
>
> I believe this problem was fixed in @mpbl <https://github.com/mpbl>
> commit fbe890d
> <https://github.com/geodynamics/specfem3d_globe/commit/fbe890d4377e9a3ae2130fa5c4825983d680f7d9>
> but reintroduced in @danielpeter <https://github.com/danielpeter> commit
> 2051275
> <https://github.com/geodynamics/specfem3d_globe/commit/2051275255ba272182f29be68539eea23e36584e>.
> I am not sure why buildbot didn't catch these errors. Maybe its because
> I just updated the Intel compilers and the old ones didn't catch the
> mistakes? I'll investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/379>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
