### ISSUE TITLE
Clarify and/or limit minimum version of CUDA requirement

### ISSUE THREAD

**Issue by QuLogic** [geodynamics/specfem3d_globe#402]
I have tried to compile the latest devel (e555897c215956c65072979637a21adc14d2c176) with various CUDA compilers, and have had trouble with several of them. According to `configure.ac`, it appears that one should be able to use CUDA 4 and up. However, I am unable to do so.

Compiling against 3.2 and `--with-cuda` (expected failure):
```
nvcc -c /home/l/liuqy/esalesde/specfem3d_globe/src/gpu/assemble_MPI_scalar_gpu.c -o obj/assemble_MPI_scalar_gpu.cuda.o   --cudart=shared -I/scinet/gpc/mpi/openmpi/1.4.4-intel-v12.1/include -DUSE_OLDER_CUDA4_GPU -gencode=arch=compute_20,code=\"sm_20,compute_20\" -x cu -I./setup -I/home/l/liuqy/esalesde/specfem3d_globe/src/gpu/kernels.gen  -DUSE_CUDA
nvcc fatal   : Unknown option '-cudart'
make: *** [obj/assemble_MPI_scalar_gpu.cuda.o] Error 255
```

Compiling against 4.0 and `--with-cuda`:
```
nvcc -c /home/l/liuqy/esalesde/specfem3d_globe/src/gpu/assemble_MPI_scalar_gpu.c -o obj/assemble_MPI_scalar_gpu.cuda.o   --cudart=shared -I/scinet/gpc/mpi/openmpi/1.4.4-intel-v12.1/include -DUSE_OLDER_CUDA4_GPU -gencode=arch=compute_20,code=\"sm_20,compute_20\" -x cu -I./setup -I/home/l/liuqy/esalesde/specfem3d_globe/src/gpu/kernels.gen  -DUSE_CUDA
nvcc fatal   : Unknown option '-cudart'
make: *** [obj/assemble_MPI_scalar_gpu.cuda.o] Error 255
```

Compiling against 4.1 and `--with-cuda`:
```
nvcc -c /home/l/liuqy/esalesde/specfem3d_globe/src/gpu/assemble_MPI_scalar_gpu.c -o obj/assemble_MPI_scalar_gpu.cuda.o   --cudart=shared -I/scinet/gpc/mpi/openmpi/1.4.4-intel-v12.1/include -DUSE_OLDER_CUDA4_GPU -gencode=arch=compute_20,code=\"sm_20,compute_20\" -x cu -I./setup -I/home/l/liuqy/esalesde/specfem3d_globe/src/gpu/kernels.gen  -DUSE_CUDA
nvcc fatal   : Unknown option '-cudart'
```

Compiling against 5.0 and `--with-cuda=cuda5`:
```
nvcc -c /home/l/liuqy/esalesde/specfem3d_globe/src/gpu/assemble_MPI_scalar_gpu.c -o obj/assemble_MPI_scalar_gpu.cuda.o   --cudart=shared -I/scinet/gpc/mpi/openmpi/1.4.4-intel-v12.1/include -dc -gencode=arch=compute_35,code=\"sm_35,compute_35\" -x cu -I./setup -I/home/l/liuqy/esalesde/specfem3d_globe/src/gpu/kernels.gen  -DUSE_CUDA
nvcc fatal   : Unknown option '-cudart'
```

Compiling against 5.5 and `--with-cuda=cuda5` works!

Compiling against 6.0 and `--with-cuda=cuda5` works! (but maybe a `cuda6` option should be added like in `specfem3d`.)

**Comment by komatits** [comment]
Maybe Daniel @danielpeter ?

**Comment by danielpeter** [comment]
hi all,

we should recommend a CUDA version > 5.5. this is currently available on HPC centers at CSCS and ORNL and the code works with it. i'll put a sentence in the docu...

best,
daniel

**Comment by komatits** [comment]
Hi Daniel @danielpeter  ,

Thanks! Maybe also print a warning to the screen if CUDA version < 5.5?

Does this apply to 2D and 3D_Cartesian as well? if so we should update them as well.

Thanks,
Dimitri.

**Comment by komatits** [comment]
Closing the issue because Daniel @danielpeter will do it.
