### ISSUE TITLE
ASDF output broken with NTSTEP_BETWEEN_OUTPUT_SEISMOS < NTSTEP

### ISSUE THREAD

**Issue by QuLogic** [geodynamics/specfem3d_globe#419]
When settings `OUTPUT_SEISMOS_ASDF` and `NTSTEP_BETWEEN_OUTPUT_SEISMOS` to something less than the total time steps, then the resulting file only contains `NTSTEP_BETWEEN_OUTPUT_SEISMOS` steps. If the number of timesteps is not divisible by that number, then you only get the remainder's worth of steps. It seems that instead of appending seismograms, it completely recreates the file with each chunk of data thereby losing everything but the last chunk.

Also, I'm kind of confused about the meaning of this ASDF output. It uses ADIOS, but I had heard there was a movement away from that due to speed issues (which seems to be true, depending on how often it's set to write.)

**Comment by jas11** [comment]
This ASDF output is the old version that will be replaced by the hdf5 version once I have the SEIS_PROV provenance working with the solver. I estimate by early next week that should be done.

**Comment by QuLogic** [comment]
I kind of expected that. I think if it's not really ready, maybe it shouldn't be one of those advertised "new features".

**Comment by komatits** [comment]
Maybe @jas11 ?

**Comment by jas11** [comment]
This is fixed in the new writer on my branch. I haven't merged it with the official repository yet because I am waiting testing to finish.

**Comment by komatits** [comment]
Thanks! Closing it then.
