### ISSUE TITLE
Minor bug in get_attenuation.f90?

### ISSUE THREAD

**Issue by kuangdai** [geodynamics/specfem3d_globe#445]
Location:
src/specfem3D/get_attenuation.f90
subroutine get_attenuation_memory_values

Should the last coefficient in the Taylor series of "betaval" be 30 but not 24? They are actually (2!/1, 3!/2, 4!/3, 5!/4) = (2, 3, 8, 30). Anyway, the influence of this forth order term should be ignorable.

**Comment by komatits** [comment]
Hi !

Let me cc Zhinan.

If I remember correctly the 1/24 factor comes from eq (38) of Carcione 
and Wang (1993) (available at https://www.lma.cnrs-mrs.fr/Filez/5wd8 ), 
for delta_4 you get 1/(6*2*2) i.e. 1/24. But I did this a long time ago 
thus do not hesitate to doublecheck.

Thanks,
Dimitri.

On 10/27/2015 06:26 PM, kuangdai wrote:
> Location:
> src/specfem3D/get_attenuation.f90
> subroutine get_attenuation_memory_values
>
> Should the last coefficient in the Taylor series of "betaval" be 30 but
> not 24? They are actually (2!/1, 3!/2, 4!/3, 5!/4) = (2, 3, 8, 30).
> Anyway, the influence of this forth order term should be ignorable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/445>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
