### ISSUE TITLE
Apache License is incompatible with GPL2

### ISSUE THREAD

**Issue by QuLogic** [geodynamics/specfem3d_globe#476]
This is mostly an issue for @jas11.

I noticed that two files you added, [read_adjoint_sources_ASDF.f90](https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/read_adjoint_sources_ASDF.f90) and [write_output_ASDF.f90](https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90) also contain an Apache license header. Is this intended to be some sort of dual-licensing scheme (i.e., the user may pick one)? 

The Apache license and GPLv2 are [not compatible](http://www.gnu.org/licenses/license-list.en.html#apache2). The Apache license and GPLv3 _are_ compatible, so because of the "or later" clause in SPECFEM3D_GLOBE, this makes SPECFEM3D_GLOBE effectively GPLv3 _if_ both licenses are to be adhered to at the same time.

However, I'm not so sure that was intended. Would it be possible to re-license your files under just GPLv2, or specify that it's dual license (i.e., either-or)? Since the copyright is for "ASDF developers", you should also ask any other ASDF developers who have touched these files.

**Comment by komatits** [comment]
Hi all,

yes, let us use GPL v2+ as in the rest of the code

(We ruled out switching to GPL v3 a few years ago.)

Thanks,
Dimitri.

On 03/03/2016 01:47, Elliott Sales de Andrade wrote:
> This is mostly an issue for @jas11 <https://github.com/jas11>.
>
> I noticed that two files you added, read_adjoint_sources_ASDF.f90
> <https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/read_adjoint_sources_ASDF.f90>
> and write_output_ASDF.f90
> <https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90>
> also contain an Apache license header. Is this intended to be some sort
> of dual-licensing scheme (i.e., the user may pick one)?
>
> The Apache license and GPLv2 are not compatible
> <http://www.gnu.org/licenses/license-list.en.html#apache2>. The Apache
> license and GPLv3 /are/ compatible, so because of the "or later" clause
> in SPECFEM3D_GLOBE, this makes SPECFEM3D_GLOBE effectively GPLv3 /if/
> both licenses are to be adhered to at the same time.
>
> However, I'm not so sure that was intended. Would it be possible to
> re-license your files under just GPLv2? Since the copyright is for "ASDF
> developers", you should also ask any other ASDF developers who have
> touched these files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/476>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi all,

I realize that the GPL v2+ license says this:

"you can redistribute it (note from Dimitri: the code) and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2 of the License, or (at your 
option) any later version"

thus we can likely re-release the whole code in GPL v3 if we want 
without asking all the past developers (which is impossible to do: not 
sure if our list is complete, and hard to get their current email 
addresses; and which is the reason why we had ruled out permanently 
switching to GPL v3).

Doing so would solve the Apache compatibility issue I guess.

Does anybody know the drawbacks (if any) of switching from v2+ to v3?
I honestly do not know what the difference is, thus let us check 
carefully before switching.

Can anybody familiar with these topics confirm that we could switch 
without having to ask all the past developers?

Thanks,
Dimitri.


On 03/03/2016 02:19, Dimitri Komatitsch wrote:
>
> Hi all,
>
> yes, let us use GPL v2+ as in the rest of the code
>
> (We ruled out switching to GPL v3 a few years ago.)
>
> Thanks,
> Dimitri.
>
> On 03/03/2016 01:47, Elliott Sales de Andrade wrote:
>> This is mostly an issue for @jas11 <https://github.com/jas11>.
>>
>> I noticed that two files you added, read_adjoint_sources_ASDF.f90
>> <https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/read_adjoint_sources_ASDF.f90>
>>
>> and write_output_ASDF.f90
>> <https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90>
>>
>> also contain an Apache license header. Is this intended to be some sort
>> of dual-licensing scheme (i.e., the user may pick one)?
>>
>> The Apache license and GPLv2 are not compatible
>> <http://www.gnu.org/licenses/license-list.en.html#apache2>. The Apache
>> license and GPLv3 /are/ compatible, so because of the "or later" clause
>> in SPECFEM3D_GLOBE, this makes SPECFEM3D_GLOBE effectively GPLv3 /if/
>> both licenses are to be adhered to at the same time.
>>
>> However, I'm not so sure that was intended. Would it be possible to
>> re-license your files under just GPLv2? Since the copyright is for "ASDF
>> developers", you should also ask any other ASDF developers who have
>> touched these files.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d_globe/issues/476>.
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by jas11** [comment]
Hi all,

I deleted the Apache license from the code. It is for the ASDF library (and still applies there). The GPLv2 will work for the ASDF related codes in SPECFEM.

James

**Comment by QuLogic** [comment]
Thanks @jas11; licensing can be annoying some times.

Fixed in #480.
