### ISSUE TITLE
read_file() in asdf writing should be optimized

### ISSUE THREAD

**Issue by wjlei1990** [geodynamics/specfem3d_globe#503]
In the write_output_ASDF.f90 file, https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90#L405, there is a function call:
```
    call read_file("setup/constants.h", sf_constants, len_constants)
    call read_file("DATA/Par_file", sf_parfile, len_Parfile)
    call ASDF_write_auxiliary_data_f(current_asdf_handle, trim(sf_constants) // C_NULL_CHAR,&
                                   trim(sf_parfile(1:len_Parfile)) // C_NULL_CHAR, ier)
```
However, this reading operation is running on all processors. So when using large number of processors, I think this may cause performance issues.  The reading should only be on master node and broadcast to all processors.

@jas11 @mpbl

**Comment by jas11** [comment]
Hi Wenjie,

You are right. I will fix this in the next update.

Cheers,
James

________________________________

**Comment by komatits** [comment]
Hi James,

Thanks! Please remember to then close the Git issue.

Thanks,
Dimitri.

On 13/07/2016 21:21, James Smith wrote:
> Hi Wenjie,
>
> You are right. I will fix this in the next update.
>
> Cheers,
> James
>
> ________________________________
> From: Wenjie Lei [notifications@github.com]
> Sent: Wednesday, July 13, 2016 9:59 AM
> To: geodynamics/specfem3d_globe
> Cc: James A. Smith; Mention
> Subject: [geodynamics/specfem3d_globe] read_file() in asdf writing
> should be optimized (#503)
>
>
> In the write_output_ASDF.f90 file,
> https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/write_output_ASDF.f90#L405,
> there is a function call:
>
> call read_file("setup/constants.h", sf_constants, len_constants)
> call read_file("DATA/Par_file", sf_parfile, len_Parfile)
> call ASDF_write_auxiliary_data_f(current_asdf_handle, trim(sf_constants)
> // C_NULL_CHAR,&
> trim(sf_parfile(1:len_Parfile)) // C_NULL_CHAR, ier)
>
>
> However, this reading operation is running on all processors. So when
> using large number of processors, I think this may cause performance
> issues. The reading should only be on master node and broadcast to all
> processors.
>
> @jas11<https://github.com/jas11> @mpbl<https://github.com/mpbl>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on
> GitHub<https://github.com/geodynamics/specfem3d_globe/issues/503>, or
> mute the
> thread<https://github.com/notifications/unsubscribe/AE4EaLh3cMrNqd63j7EZIxX94jy6nB-Aks5qVP05gaJpZM4JLguk>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/503#issuecomment-232459501>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKbnUUJl0Qb8INY51joz4FqlSEtqsks5qVTrRgaJpZM4JLguk>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by jas11** [comment]
Hi Dimitri,

I created a pull request that resolves this issue and so I will now close it.

Best,
James

**Comment by jas11** [comment]
I think you will have to close it as I don't have the authority.

**Comment by komatits** [comment]
Thanks. Done!
