### ISSUE TITLE
3D Jacobian undefined

### ISSUE THREAD

**Issue by kuangdai** [geodynamics/specfem3d_globe#539]
Dear authors,

I am running simulations at a 5 s period, with topography, ocean, and crust. I got errors "3D Jacobian undefined in recalc_jacobian_gll3D.f90" constantly, attached as error.txt. I am using UK's supercomputer Archer, and I tried many different compiler suits and options. 

I find it difficult to debug the code because this error disappears for smaller problems (e.g., 10s, NEX_XI=448) with the same parameters. 

The Par_file I am using is attached and the code is updated to the latest version. 

Thank you very much!

[Par_file.txt](https://github.com/geodynamics/specfem3d_globe/files/710847/Par_file.txt)
[error.txt](https://github.com/geodynamics/specfem3d_globe/files/711078/error.txt)

**Comment by komatits** [comment]
Hi,
It is difficult to honor tomography in great details at very high resolution without getting distorted elements; in such a case one should use a mesher (Trelis, Gmsh or similar) instead of the internal mesher for the Earth.
