### ISSUE TITLE
specfem3d_globe and cuda5 ERROR: CUDA runtime error: cudaMalloc failed

### ISSUE THREAD

**Issue by olgaus** [geodynamics/specfem3d_globe#617]
Hi!
Could you help me. I compiled specfem3d with cuda/5.5  and openmpi/1.8.4-gcc. After running of simple test i have error. 
Error testing memory allocation on device failed
Error rank 1: cudaMalloc failed: unknown error
Error testing memory allocation on device failed
Error rank 2: cudaMalloc failed: unknown error
Error testing memory allocation on device failed
Error rank 3: cudaMalloc failed: unknown error
Error: cudaMemGetInfo fails, unknown error
ERROR: CUDA runtime error: cudaMalloc failed
------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[27495,1],2]
  Exit code:    1

**Comment by komatits** [comment]
Dear all,

Probably a local installation problem? The code runs fine on other machines.

Best regards,
Dimitri.
