### ISSUE TITLE
model interpolation issues

### ISSUE THREAD

**Issue by wjlei1990** [geodynamics/specfem3d_globe#679]
Hi,

What I am trying to do is to interpolate from GLAD-M25 model (NEX=256, NCHUNKS=6, NPROC_XI=8), into a lower resolution 1 chunk model (NEX=160, NCHUNKS=1, NRPOC_XI=4), in ADIOS format.

However, there are some errors showing up in the output file.
```
  loading source model ... 
   slice number:            1  out of           64
   for parameter: reg1/vpv
   for parameter: reg1/vph
   for parameter: reg1/vsv
   for parameter: reg1/vsh
   for parameter: reg1/eta
   for parameter: reg1/rho
   slice number:            2  out of           64
   for parameter: reg1/vpv
ERROR: Error: Variable (id=4) out of bound 1(the data in dimension 1 to read is 1312000 elements from index 140733194700032 but the actual data is [0,503807999])
ERROR: Error: Variable (id=4) out of bound 1(the data in dimension 1 to read is 1312000 elements from index 140733194700032 but the actual data is [0,503807999])
ERROR: Error: Variable (id=4) out of bound 1(the data in dimension 1 to read is 1312000 elements from index 140733194700032 but the actual data is [0,503807999])
ERROR: Error: Variable (id=4) out of bound 1(the data in dimension 1 to read is 1312000 elements from index 140733194700032 but the actual data is [0,503807999])
...
```
Do you know if this is critical?

I have attached the job output log here.
[log.interpolate.121940.txt](https://github.com/geodynamics/specfem3d_globe/files/4686583/log.interpolate.121940.txt)

**Comment by wjlei1990** [comment]
I think I may figure out the bug.

The issue is caused by calling `read_adios_array_gll` to read the `model_gll.bp` file.
```
call adios_get_scalar(adios_handle, trim(array_name)//"/local_dim",local_dim, ier) 
``` 
The value of `local` in my program before and after this function call is:
```
 [reg1/vpv/local_dim] before reading local_dim=      140736722635040
 [reg1/vpv/local_dim] after reading local_dim=      140733194700032
```
And the value is constant between different runs.

However, if I initialize the `local_dim` to `0` in the `read_adios_array_gll` function:
```
integer(kind=8) :: local_dim = 0.0
```
Then it can read the `local_dim` correctly and the correct value is `1312000`.

One thing that puzzles me is why this initialization will affect the reading?

Also, there is very similiar cases in other funcitons, such as `read_adios_array_gll_int`. So I did another check in this function and found the value of `local_dim` before and after:
```
 before reading local_dim=                   50
 after reading local_dim=              1312000
```

I am guessing if the value of `local_dim` is smaller than the to-be-read-in value, then reading will give you the right value. If the initial value of `local_dim` then reading will be wrong...It might be something related to the `adios_get_scalar`, which is used to read the local_dim.

I guess this might be a dangerous behaviour of current adios functions in specfem.

**Comment by danielpeter** [comment]
great, thanks for catching this. it sounds like an initialization problem, will put an explicit one before the function calls.

**Comment by wjlei1990** [comment]
Do you want me to submit the code change? so you can review and merge it...It is just a few lines change.

**Comment by danielpeter** [comment]
it is done in commit 9ea6b70b7b940eecd2ca9ee9f7d2340950da912d

please let me know if this fixes the issue so we can close this one.

**Comment by wjlei1990** [comment]
issue resolved. Thanks :)
