### ISSUE TITLE
Switch from vtk to vtu in combine_vol_data?

### ISSUE THREAD

**Issue by icui** [geodynamics/specfem3d_globe#706]
Specfem already has this function and switching to vtu, which is much more efficient, is just a matter of changing a function name. So I was wondering if it is OK to use vtu as the default format, or is there any consideration in still keeping vtk?

**Comment by danielpeter** [comment]
the legacy VTK file format has a simple ASCII structure, thus is easy to implement and output without any need for VTK library calls/installations. being ASCII files, they are compatible to be moved and visualized on different systems/architectures. the drawback is that ASCII files tend to become quite large.

the VTU format can have both, an ASCII and a binary format. obviously, the ASCII format doesn't save much space and therefore is similar to the VTK format. there is a benefit in terms of file size for the binary VTU format. the implementation is again avoiding the need for VTK library calls/installations, however becomes now architecture dependent, either storing numbers in a big endian or little endian representation. thus in principle, we can run into problems when the files are created on a different system than the one visualized on. this is a typical use case, where the model is generated on a large cluster, but the mesh files are visualized on a personal workstation. 

anyway, if you know that your systems are compatible, then go ahead and switch it. if you prefer, we probably could add another compilation target for VTU output files, creating an additional `xcombine_vol_data_vtu` binary - would that work for you? :)

**Comment by icui** [comment]
Thanks for the reply. It would be great to have an additional `xcombine_vol_data_vtu` so that I don't have to change the source code to get the VTU output.

**Comment by danielpeter** [comment]
VTU binary targets have been added with PR #755

**Comment by icui** [comment]
Thanks for the quick fix! I've tried `xcombine_vol_data_vtu` and it works as expected.
