### ISSUE TITLE
Changing event order in CMTSOLUTION will make the seismogram look different

### ISSUE THREAD

**Issue by icui** [geodynamics/specfem3d_globe#718]
When including multiple events in CMTSOLUTION, the order of the events actually have a noticeable impact on the seismograms, and the impact is dependent on the number of events included. Zhendong suggested that it might has something to do with the process of locating sources, and that there are some initialization issued in the source location subroutine.
<img width="575" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/44066357/105402352-510f3b80-5bf5-11eb-858c-34b2fa4f5db8.png">

**Comment by icui** [comment]
I've followed Zhendong's fix and now the two seismograms look the same now:

1) Change the simultaneous locating to 1.
https://github.com/geodynamics/specfem3d_globe/blob/devel/setup/constants.h.in#L265
2) Put r0 = R_UNIT_SPHERE before the depth in the source code here.
https://github.com/geodynamics/specfem3d_globe/blob/devel/src/specfem3D/locate_sources.f90#L301

**Comment by danielpeter** [comment]
fixed in PR #719
