### ISSUE TITLE
The synthetics is all 0 for CUDA10 and CUDA11 

### ISSUE THREAD

**Issue by ziyixi** [geodynamics/specfem3d_globe#733]
I am using the development version and trying to compile it with CUDA11. The code can be successfully compiled and the executable can be successfully run. However, when I check the synthetics, everything is 0. 

Then I test different versions of the CUDA, and find CUDA9 works well while CUDA10 has the same problem. What's more, I check output_solver.txt, and find that for the problematic versions, no matter what time step is, it shows:
```
 Max norm displacement vector U in solid in all slices for forward prop. (m) =    0.00000000
 Max non-dimensional potential Ufluid in fluid in all slices for forward prop. =    0.00000000
 Max of strain, eps_trace_over_3_crust_mantle =   0.00000000
 Max of strain, epsilondev_crust_mantle  =   0.00000000
```
And for CUDA9, it will show something like:
```
 Max norm displacement vector U in solid in all slices for forward prop. (m) =    9.24328249E-03
 Max non-dimensional potential Ufluid in fluid in all slices for forward prop. =    1.38953807E-14
 Max of strain, eps_trace_over_3_crust_mantle =   0.00000000
 Max of strain, epsilondev_crust_mantle  =   1.39851954E-06
```

I have attached my CMT_SOLUTION, the Par_file, and the STATIONS below.

[log.zip](https://github.com/geodynamics/specfem3d_globe/files/6402457/log.zip)

The compiler versions in the zip file:
1. GCC/7.3.0, CUDA/9.2.88, OpenMPI/3.1.1
2. GCC/8.2.0, CUDA/10.1.105, OpenMPI/4.0.0
3. intel/2020.1.217, CUDA/11.0.2, OpenMPI/4.0.3

I have also tested other compiler versions on another cluster, they all have the same problem:
1. intel/19.0.5.281, cuda/11.0.2, openmpi/4.0.4
2. intel/19.0.5.281, cuda/10.2, openmpi/4.0.4
3. GCC/8.3.0, cuda/11.0.2, openmpi/4.0.4
4.  GCC/8.3.0, cuda/10.2, openmpi/4.0.4

**Comment by danielpeter** [comment]
what GPU card are you using and what nvcc flags are set when compiling?

**Comment by ziyixi** [comment]
I am using Tesla V100. An example of my configuration is:
```
./configure FC=ifort CC=icc MPIFC=mpif90  --with-cuda=cuda11 CUDA_LIB=/opt/software/CUDAcore/11.0.2/lib64 CUDA_INC=/opt/software/CUDAcore/11.0.2/include
```
I have not touched nvcc.

**Comment by danielpeter** [comment]
right, the configuration option for your Volta V100 should always be: `..--with-cuda=cuda9`

the SPECFEM configuration option `--with-cuda=cudaX` acts as a specifier for your GPU card, not your CUDA toolkit version. Volta V100 cards have been introduced and supported with CUDA 9. thus, even when you update your CUDA toolkit version to CUDA 11, still use `--with-cuda=cuda9` to compile code for your target architecture V100.

**Comment by ziyixi** [comment]
Thanks! I tested `--with-cuda=cuda9` with CUDA11, and it works.
