### ISSUE TITLE
BOAST version used?

### ISSUE THREAD

**Issue by icui** [geodynamics/specfem3d_globe#767]
I've tried BOAST 2.0.0 and 2.1.0 but neither is consistent with the existing files in kernels.gen. Two main differences are:
1. ```BOAST::HIP``` is undefined, I have to manually define a BOAST::HIP value
2. ```:operator => "<"``` seems to be ignored. When parsing this line:
```
print For(iinterface, 0, num_interfaces, :operator => "<") 
```
both BOAST 2.0.0 and BOAST 2.1.0 will yield
```
for (iinterface = 0; iinterface <= num_interfaces; iinterface += 1)
```
but the corresponding line in kernels.gen is
```
for (iinterface = 0; iinterface < num_interfaces; iinterface += 1)
```

I was wondering if there's extra configuration needed to reproduce kernels.gen?

**Comment by danielpeter** [comment]
did you try out with the current github version of BOAST? use the master branch from:
https://github.com/Nanosim-LIG/boast

**Comment by icui** [comment]
Yes, the GitHub version works.
