### ISSUE TITLE
save_kernels.F90 in 8.0.0

### ISSUE THREAD

**Issue by daniuhua** [geodynamics/specfem3d_globe#769]
In line 1280 and 1281 in save_kernels.F90 in 8.0.0, for each iteration in NSPEC, NGLLX, NGLLY, NGLLZ, the function would compute minus rho_kl_crust_mantle and cijkl_kl_crust_mantle instead of cijkl_kl_crust_mantle(:,i,j,k,ispec), rho_kl_crust_mantle(i,j,k,ispec), which makes this part super slow. And it's not clear to me why we need to compute such minus for millions of times on the whole cijkl_kl_crust_mantle. I suspect here it should be cijkl_kl_crust_mantle(:,i,j,k,ispec) =- cijkl_kl_crust_mantle(:,i,j,k,ispec) and rho_kl_crust_mantle(i,j,k,ispec) = -rho_kl_crust_mantle(i,j,k,ispec)?

By the way, since this part does not appear in the 7.0.0, could I know why we need to multiply a minus sign here? And is there any other changes made to the code in the last month? I tried to use the official 7.0.0 version, but with the new machine I'm using, I often encounter some strange errors during xmeshfem3D (sometimes it works sometimes doesn't), but never encountered such issue with the development 8.0.0 version, which made me switched to this version. However, since it is the "development" version, I would really like to know if there are any new changes that have been made to make sure for example the calculated kernels are correct.

**Comment by danielpeter** [comment]
thanks for pointing out those lines! they don't look right. and yes, it should be done per GLL point, like:
```
..
           rho_kl_crust_mantle(i,j,k,ispec) = - rho_kl_crust_mantle(i,j,k,ispec)
           cijkl_kl_crust_mantle(i,j,k,ispec) = - cijkl_kl_crust_mantle(i,j,k,ispec)
..
```
the minus sign appears in all kernel definitions and gets added only at the very end of the kernel computations. the kernel contributions computed in compute_kernels_**() routines are all kept positive, so the minus sign is added only before saving the kernel arrays to disk. 

version 7.0.0 handles the minus sign differently for fully anisotropic kernels, and only adds it in the write statements: `write(IOUT) - rho_kl_crust_mantle` which makes this error prone when updating the routine. so this special handling has been replaced and added into the do-loops above to be more explicit, but obviously was missing the array indexing. 

thanks for spotting! will be corrected in the next PR...

**Comment by daniuhua** [comment]
Thank you for this information!
